[project]
name = "digital-photobomber"
version = "0.1.0"
description = "Creates an image and use array slicing to copy a small part onto multiple other positions in the same thing."
readme = "README.md"
authors = [
    { name = "memothelemo", email = "dev@memothelemo.xyz" }
]
requires-python = ">=3.12"
dependencies = [
    "opencv-contrib-python>=5.0.0.93",
]

[project.scripts]
digital_photobomber = "digital_photobomber:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
