[project]
name = "image-activity"
version = "0.1.0"
description = "Loads, displays, and saves an image"
readme = "README.md"
authors = [
    { name = "memothelemo", email = "dev@memothelemo.xyz" }
]
requires-python = ">=3.12"
dependencies = [
    "opencv-contrib-python>=5.0.0.93",
]

[project.scripts]
image-activity = "image_activity:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
